---
- hosts: localhost
  vars:
    ssh_source_key: "./vaults/id_ed25519"
    ssh_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  become: yes
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - name: Install System Packages
      become: true
      apt:
        name:
          - curl
          - gpg
          - wget
      tags:
        - install
        - core

    - include: tasks/zsh.yml
    - include: tasks/ssh.yml
    - include: tasks/nvim.yml
    - include: tasks/dotfiles.yml
    - include: tasks/folders.yml
    - include: tasks/node.yml # Depend on zsh and dotfiles
