---
- hosts: localhost
  vars:
    installation_path: "{{ lookup('env', 'HOME') }}/.pbl/dotfiles"
    ssh_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    ssh_source_key: "{{installation_path}}/vaults/id_ed25519"

    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d

  become: yes
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - name: Install System Packages
      become: true
      apt:
        name:
          - curl
          - gpg
          - wget
      tags:
        - install
        - core

    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/folders.yml
    - include_tasks: tasks/node.yml # Depend on zsh and dotfiles
    - include_tasks: tasks/ruby.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/brave.yml
    - include_tasks: tasks/spotify.yml
