---
- name: Install System Packages
  become: true
  apt:
    name:
      - stow
  tags:
    - install
    - dotfiles

- name: Clone pablorc/git-helpers
  ansible.builtin.git:
    repo: https://github.com/pablorc/git-helpers
    dest: "{{ lookup('env', 'HOME') }}/.pbl/git-helpers"
  tags:
    - install
    - git
    - dotfiles

- name: Stow all dotfiles
  become_user: pablorc
  shell: |
    cd {{ installation_path }}/stow
    for d in *; do
     stow -t {{ lookup('env', 'HOME') }} $d
    done
  tags:
    - dotfiles
