---
- name: Install System Packages
  become: true
  apt:
    name:
      - stow
  tags:
    - install
    - dotfiles
- name: Stow all dotfiles
  become_user: pablorc
  shell: |
    cd {{ lookup('env', 'HOME') }}/.pbl/stow
    for d in *; do
     stow -t {{ lookup('env', 'HOME') }} $d
    done
  tags:
    - dotfiles
