# Not working
---
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh >o
  tags:
    - install
    - node
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
  tags:
    - install
    - node

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh&& nvm install $(nvm ls-remote | tail -1)"
  tags:
    - install
    - node
