# Not working
---
- name: Install nvm
  become_user: pablorc
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  tags:
    - install
    - node

- name: Install last node
  become_user: pablorc
  shell: |
    echo "nvm install node" > {{ lookup('env', 'HOME') }}/.nvm_install
    chmod +x {{ lookup('env', 'HOME') }}/.nvm_install
    zsh -i "{{ lookup('env', 'HOME') }}/.nvm_install"
    rm {{ lookup('env', 'HOME') }}/.nvm_install
  tags:
    - install
    - node
