---
- name: Add Neovim unstable APT repo
  shell: "add-apt-repository -y ppa:neovim-ppa/unstable"
  become: true
  tags:
    - nvim

- name: Install neovim
  become: true
  apt:
    update_cache: yes
    name:
      - neovim
      - ripgrep
  tags:
    - nvim
    - apt

- name: Clone pablorc/neovimfiles
  become_user: pablorc
  ansible.builtin.git:
    repo: https://github.com/pablorc/neovimfiles
    dest: "{{lookup('env', 'HOME')}}/.pbl/stow/nvim/.config/nvim"
  tags:
    - nvim
