---
- name: Install System packages for RVM
  become: true
  apt:
    name:
      - gnupg2
  tags:
    - ruby

- name: Install RVM
  become_user: pablorc
  shell: |
    gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl -sSL https://get.rvm.io | bash -s stable
  tags:
    - ruby
