---
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
    - vault

- name: Install ssh key
  copy:
    src: "{{ ssh_source_key }}"
    dest: "{{ ssh_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
    - vault

- name: Install ssh key public
  copy:
    src: "{{ ssh_source_key }}.pub"
    dest: "{{ ssh_dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
    - vault

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - dotfiles
    - install
    - ssh
    - vault

- name: chown .ssh
  shell: chown -R pablorc .ssh/ && chgrp -R pablorc .ssh/
  tags:
    - dotfiles
    - install
    - ssh
    - vault
