---
- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks ["install", "zsh"]

- name: Install oh-my-zsh
  become_user: pablorc
  shell:
    cmd: curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | sh

- name: Change shell to zsh
  user:
    name: pablorc
    shell: /bin/zsh
  tags: *tags_for_zsh_tasks

- name: Remove default .zshrc
  become_user: pablorc
  shell:
    cmd: rm {{ lookup('env', 'HOME') }}/.zshrc

- name: Install eza
  become: true
  shell: |
    sudo mkdir -p /etc/apt/keyrings
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    sudo apt update
    sudo apt install -y eza

- name: Install Starship
  shell: "curl -sS https://starship.rs/install.sh  | FORCE=true sh"

- name: Clone pablorc/git-helpers
  ansible.builtin.git:
    repo: https://github.com/pablorc/git-helpers
    dest: "{{ lookup('env', 'HOME') }}/.pbl/stow/git-helpers/.pbl/git-helpers"
  tags:
    - install
    - git

- name: Install .pbl_env
  become_user: pablorc
  copy:
    src: "{{ lookup('env', 'HOME') }}/vaults/.pbl_env"
    dest: "{{ lookup('env', 'HOME') }}/.pbl_env"
    mode: 0600
  tags:
    - dotfiles
    - install
    - vault
