
format = '$all$fill$ruby$nodejs$time$line_break$character'

[gcloud]
disabled = true

[package]
disabled = true

[time]
format = '⌚️ [$time]($style)'
time_format = '%T' # %R to not have seconds
disabled = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[nodejs]
format = '[$symbol($version )]($style)'

[ruby]
format = '[$symbol($version )]($style)'

[fill]
symbol = ' '
