$mainMod = SUPER

# Theme
source = ~/.config/hypr/themes/mocha.conf
$background =  ~/Pictures/wallpapers/silksong-caravana-pulgas.jpg

# My configs
source = ~/.config/hypr/pablorc/default.conf
source = ~/.config/hypr/pablorc/variables.conf
source = ~/.config/hypr/pablorc/ui.conf
source = ~/.config/hypr/pablorc/keyboard.conf
source = ~/.config/hypr/pablorc/keybinds.conf

# CachyOS (more or less) default confs, still to check
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/variables.conf

# Init processes
source = ~/.config/hypr/pablorc/autostart.conf
