# General
$filemanager = dolphin
$applauncher = walker
$terminal = kitty
$idlehandler = hypridle
$browser=firefox

# Screenshots
$shot-region = grimblast copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output

