# General
$filemanager = dolphin
$applauncher = pgrep -x wofi >/dev/null 2>&1 && killall wofi || wofi --dmenu --show drun
$terminal = kitty
$idlehandler = hypridle
$browser=firefox

# Screenshots
$shot-region = grimblast copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output

$background =  /home/zote/Pictures/wallpapers/silksong-caravana-pulgas.jpg

