# Fast access
bindd = $mainMod, B, Opens web browser ($browser), exec, $browser
# bindd = $mainMod, P, Opens terminal for project , exec, $terminal "$(find ~/Work ~/Pets -type d -maxdepth 2 | fzf) "
# bind = $mainMod, Z, exec, pkill waybar || waybar

bindd = $mainMod, T, Opens your preferred terminal emulator ($terminal), exec, $terminal
bindd = $mainMod, F, Opens your preferred filemanager ($filemanager), exec, $filemanager
bindd = $mainMod, Q, Closes (not kill) current window, killactive,
# bindd = $mainMod SHIFT, M, Exits Hyprland by terminating the user sessions, exec, loginctl terminate-user ""
bindd = $mainMod, V, Switches current window between floating and tiling mode, togglefloating,
bindd = $mainMod, SPACE, Runs your application launcher, exec, $applauncher


