# Fast access
bindd = $mainMod, B, Opens web browser ($browser), exec, $browser
# bindd = $mainMod, P, Opens terminal for project , exec, $terminal "$(find ~/Work ~/Pets -type d -maxdepth 2 | fzf) "
bind = $mainMod, Z, exec, pkill waybar || waybar


