general {
  border_size = 3
  gaps_in = 5
  gaps_out = 5

  col.active_border = $yellow
  col.inactive_border = $base

  layout = dwindle # master|dwindle
}

decoration {
  rounding= 10
  inactive_opacity = 0.9

  blur {
    size = 5
    noise = 0.07
  }
}
