$background =  /home/manny-calavera/Pictures/wallpapers/silksong-campanilla.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-reto-madre-seda.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-acto3-1.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-acto3-2.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-banco-abismo.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-campana-abismo.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-caravana-pulgas.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-hornet-flores.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-lace-flores.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-madre-seda.jpg
# $background =  /home/manny-calavera/Pictures/wallpapers/silksong-pelea-flores.jpg
# $background = /home/manny-calavera/Pictures/wallpapers/silksong-reto-karmelita.jpg

